### PR TITLE
enable_at_startup (StartupTask) extension

### PR DESCRIPTION
**Pull request by HevelMc**

### CODE REVIEW

**Comment by YehudaKremer** [comment]
Hello @HevelMc 

Cool feature, works for me:
image

Thank you 👍

**Comment by YehudaKremer** [comment]
Published new version ([3.3.0](https://pub.dev/packages/msix)) with this feature.
Thanks again for your donation to this project.

**Comment by YehudaKremer** [comment]
With this feature, I was able to create a [windows widget](https://github.com/YehudaKremer/smart_watch_widget) that opens when Windows starts.

Thanks again @HevelMc .

**Comment by Tienisto** [comment]
Are we able to toggle this programmatically?
I want to add this in the settings page of the app. However, the `launch_at_startup` does not support msix apps.

**Pull request merged**
