### PR TITLE
Update the main package description

### PR DESCRIPTION
**Pull request by YehudaKremer**
Hello Brett

I would love to hear your opinion on whether to add more details about the MSIX format in the general description
of this package, or leaving a short without changes.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
I like this change

**Comment by domesticmouse** [comment]
> I would love to hear your opinion on whether to add more details about the MSIX format in the general description
> of this package, or leaving a short without changes.

This is always a tricky thing to balance. Adding information is always good until there is too much to digest.

**Comment by YehudaKremer** [comment]
I agree Brett,

I remember just starting to look for some option to install flutter on window and i did not know at all what is MSIX.
So I thought it would be worth to give at least an opening sentence about what is MSIX..

On the other hand, as you wrote, we don't want to add unnecessary text.. 

So I left this hard decision to you:) 👍

**Comment by YehudaKremer** [comment]
> Adding information is always good until there is too much to digest

Also that why i used **collapse** in the [configuration section](https://github.com/YehudaKremer/msix#gear-configuration-optional) to hide the big configuration options table

**Pull request merged**
