### PR TITLE
add new configuration option 'build-number'

### PR DESCRIPTION
**Pull request by mmattes**
We want to use your msix package in our ci pipeline which runs multiple times a day. Unfortunately the microsoft store has some issues why deploying multiple releases in a flight track doesnt work out for us. Due to that we want to distribute the msix for our test or dev environment outside of the store. Unfortunatley, if the version number does not increase then msix will not update anything. Due to that i have added a new configuration option 'build-number' which more or less works the same as the flutter build option --build-number

### CODE REVIEW

**Review by YehudaKremer — CHANGES_REQUESTED** [review]
Hello @mmattes 

Thank you for this PR.

Unfortunately when I try it on a new project by running the command: `flutter pub run msix:create` I get the error:

```PS
PS C:\Users\*\Desktop\flutter_application_4> flutter pub run msix:create
running "flutter build windows --build-number 0"...  

Unhandled exception:
Target file "--build-number 0" not found.

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:59:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:26:9)
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:103:31)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:98:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:57:5)
<asynchronous suspension>
#5      main (file:///C:/Users/*/Desktop/msix/bin/create.dart:4:3)
<asynchronous suspension>
pub finished with exit code 255

```

**Comment by mmattes** [comment]
Hi @YehudaKremer, 

thank you for your feedabck, i have just fixed this issue, please try it again.

**Comment by YehudaKremer** [comment]
Hello again, sorry for the delay

I would like to hear your opinion too on my suggestion https://github.com/YehudaKremer/msix/pull/160#issuecomment-1403210163

**Comment by mmattes** [comment]
Hi @YehudaKremer,

reading through your sugesstion at work today it totally made sense to me why i actually wanted to start working on it tonight but looking at my problem and solution this will not work for me as i need to have the build-number also within the msix files. So my new configuration option is not only related to the flutter build command. 

I have thought of another solution but i am not that deep into dart/flutter to actually build that. The by the flutter build command generated assembly the .exe contains the version number. I thought of reading out this version number and using this for the msix package you create. If this would be done by default then your suggestion to have a generic way to pass extra arguments to the flutter build is totally valid.

**Comment by YehudaKremer** [comment]
Hello

I publish a new version (3.8.0) with the new `windows_build_args` config option.
[CHANGELOG](https://github.com/YehudaKremer/msix/blob/main/CHANGELOG.md#380)

**Comment by mmattes** [comment]
Thank you but as stated this does not help in my case as i want the last bit of the version number within the msix to be not 0.

**Comment by YehudaKremer** [comment]
Hey

Here is how you can have control of the msix-version: https://github.com/YehudaKremer/msix/blob/main/doc/msix_version.md
and for the assembly-version you can use the `windows build args` config.

Is there another version field other than those two?

**Pull request closed without merging**
