### PR TITLE
Command-Line Arguments extensions

### PR DESCRIPTION
**Pull request by dmk-rib**
This pull request contains Command-Line Arguments extensions: _--password (already exists)_, _--version (msix version)_, _--certificate_ (path to the certificate). 
Msix package is convenient to use for construction of msix in Azure Build Pipeline. But it is not possible to assign an automatically-incremented version and specify the path to the release certificate from CL ...It was added here.

@YehudaKremer, could you make a package with these extensions?

### CODE REVIEW

**Review by YehudaKremer — CHANGES_REQUESTED** [review]
@dmk-rib Thank you again for your contributions to this package.

Very nice code! 

about: https://github.com/YehudaKremer/msix/pull/33/commits/c24dcd2a049b01dcbbc4bbc1c8f990f291ea9279#diff-58bb726ab4bd757fbbba80a3457a5429149a61ffa2bf86f72a4632c04728cd3eR174-R179
we may want to keep the expansion functions in one place (utils.dart)
what do you think?

**Comment by dmk-rib** [comment]
@YehudaKremer, thank you. It makes sense. One more [commit ](https://github.com/YehudaKremer/msix/pull/33/commits/7ed56a8f0727c1248837c155fc0ae357b082d101) was added

**Review by YehudaKremer — APPROVED** [review]
great!

**Comment by YehudaKremer** [comment]
I'll post a pub new pub version in a few minutes

**Comment by YehudaKremer** [comment]
@dmk-rib i publish new version to pub 1.0.2

thank you again :)

**Comment by dmk-rib** [comment]
Thanks for the quick response!

**Pull request merged**
