### PR TITLE
Add support for extension windows.appUriHandler

### PR DESCRIPTION
**Pull request by chirag729**
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking

### CODE REVIEW

**Comment by chirag729** [comment]
@YehudaKremer Could this be merged and released please?

**Comment by YehudaKremer** [comment]
Hello @chirag729 

I published a new version ([3.6.0](https://pub.dev/packages/msix)) with your added feature.

A few additions to your commit:
- added option to set multiple hosts
- changed the config name from `app_uri_handler_host` to `app_uri_handler_hosts`
- added documentation see the msix configuration table

Thank you for your contribution 👍

**Comment by chirag729** [comment]
@YehudaKremer Thanks for reviewing this PR so quickly

**Comment by IsaiChristian** [comment]
Hi, how do I use this options? I set them up in the YML like this :
```
  protocol_activation: http, https
  app_uri_handler_hosts: domain.com, appwrite.domain.com
```

but I dont know how to make it work the app is open once a link is click ( on my test it didnt work so I wonder if I need to do something  extra on my flutter code)

**Comment by chirag729** [comment]
@IsaiChristian Follow the instructions here: https://learn.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking

For my own app I ended up not using app_uri_handler_hosts. Just protocol_activation: myappname was enough

**Pull request merged**
