### PR TITLE
Add support for Dart code obfuscation.

### PR DESCRIPTION
**Pull request by theLee3**
This adds support for Dart code obfuscation via command line args or pubspec.yaml configuration. The args are passed to the `flutter build windows` command.

### CODE REVIEW

**Review by YehudaKremer — COMMENTED** [review]
Hello, thanks for the PR!

Is obfuscate supported in window ?
image

**Comment by theLee3** [comment]
It is my understanding that it is supported, but that the doc at that link is out of date, as seen here: flutter/flutter#4154. This may be incorrect, but I have confirmed that the command runs with the flags and outputs to the symbol directory.

**Comment by theLee3** [comment]
There's also [this](https://github.com/flutter/flutter/issues/99477) from March '22, resolving an issue with obfuscation for Windows.

I discovered it while trying to find a straight answer on whether or not it is actually implemented.

**Comment by YehudaKremer** [comment]
Hello

Very sorry for the delay, I was cut up with work.

Look, instead of adding a bunch of flutter build-CLI options or commands to the msix package,
maybe we can add one generic option to add any args or flags that will pass out to the `windows build` command that this package runs

for example in the msix YAML configuration
```yaml
msix_config:
  version: 1.2.3.4
  windows_build_args: '--obfuscate --split-debug-info=/<project-name>/<directory>'
```

btw, your pr looks great 👍 
please I would like to hear your opinion on my suggestion

**Comment by theLee3** [comment]
No problem.

I think that is a great approach! I actually had the same thought when working with the package. That way, as Flutter evolves, new `windows build` arguments will not require an update to the package.

Thank you for the pr acknowledgement 😄

**Pull request closed without merging**
